local opt = vim.opt

opt.number = true
opt.relativenumber = false      -- fixed numbers, they don't shift with the cursor
opt.mouse = "a"
opt.clipboard = "unnamedplus"   -- system clipboard; needs xclip or wl-clipboard
opt.ignorecase = true
opt.smartcase = true
opt.hlsearch = false
opt.incsearch = true
opt.expandtab = true
opt.shiftwidth = 2
opt.tabstop = 2
opt.autoindent = true
opt.wrap = false
opt.backspace = "indent,eol,start"
opt.splitbelow = true
opt.splitright = true
opt.termguicolors = true
opt.signcolumn = "yes"
opt.scrolloff = 8
opt.updatetime = 250
opt.undofile = true             -- persistent undo across sessions
